---
title: "Nonparametric Analysis of US Dairy Production and Consumption"
subtitle: "Spatial GAM"
author:
    - "Teo Bucci^[teo.bucci@mail.polimi.it]"
    - "Filippo Cipriani^[filippo.cipriani@mail.polimi.it]"
    - "Gabriele Corbo^[gabriele.corbo@mail.polimi.it]"
    - "Andrea Puricelli^[andrea3.puricelli@mail.polimi.it]"
output:
    pdf_document:
        toc: true
        toc_depth: 3
        number_section: true
        #keep_md: TRUE
    html_document:
        toc: true
        toc_float: true
        number_sections: true
date: "2023-02-17"
editor_options:
    chunk_output_type: inline
---
  
```{r setup, echo = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    dev = c('pdf'),
    fig.align = 'center',
    fig.path = 'output/',
    fig.height = 6,
    fig.width = 12
)
```

# Load libraries and data

```{r, message=FALSE}
library(ISLR2)
library(car)
library(sp)
library(mgcv)
library(rgl)
library(splines)
library(pbapply)
library(devtools) 
library(visreg)
library(ggplot2)
library(mgcViz)
```

```{r}
source("05-Prepare-data-spatial.R", echo=F)
```

# Model 1: PREDICT ON INTERACTION BETWEEN COORDINATES

```{r}
mod2d <- mgcv::gam(log(Value) ~ s(y,x), data = all_sales_county_2007, method = "REML")
summary(mod2d)
par(mfrow=c(1,1))
plot(mod2d,scheme=2,pages=0,select = 1, 
     main = "Smooth coefficients of interaction", 
     xlab = "longitude",ylab = "latitude")
b <- getViz(mod2d)
pl <- plot(sm(b, 1)) + l_fitRaster() + l_fitContour() +
    geom_polygon(data = map_data ("state"), 
                 aes(x=long, y = lat,group=group),
                 fill=NA,color="black",lwd = 0.7,inherit.aes = F) +
  ggtitle("Smooth coefficients of interaction") + 
  xlab("Longitude") + ylab("Latitude")
pl
x_grid <- map_data ("state")$long
y_grid <- map_data ("state")$lat
```

```{r,warning=FALSE}
# Make the perspective plot with error surfaces
vis.gam(mod2d, view = c("y", "x"), 
        plot.type = "persp", se = 2)
# Rotate the same plot
vis.gam(mod2d, view = c("y", "x"),
        plot.type = "persp", se = 2, theta = 135)
# Make plot with 10% extrapolation
vis.gam(mod2d, view = c("y", "x"),
        plot.type = "contour", too.far = 0.25)
dat1 <- all_sales_county_2007
coordinates(dat1) <- c("y","x")
points(dat1)
```

# Model 2: PREDICT ON INTERACTION BETWEEN COORDINATES AND POPULATION

```{r}
tensor_mod2 <- gam(log(Value) ~ s(y, x)+s(log(Population)), 
                  data = all_sales_county_2007, method = "REML")

# Summarize and plot
summary(tensor_mod2)
plot(tensor_mod2,pages=1)
par(mfrow=c(1,2))
plot(tensor_mod2,scheme=2,pages=0,select = 1,
     main = "Smooth coefficients of interaction", 
     xlab = "longitude",ylab = "latitude")
plot(tensor_mod2,scheme=2,pages=0,select = 2, 
     main = "Population effect", ylab = "s(log(Population))")

plot(tensor_mod2, scheme = 2, pages =0,select=1)

par(mfrow=c(1,1))
plot(tensor_mod2,scheme=2,pages=0,select = 1, 
     main = "Smooth coefficients of interaction", 
     xlab = "longitude",ylab = "latitude")

b <- getViz(tensor_mod2)
pl <- plot(sm(b, 1)) + l_fitRaster() + l_fitContour() +
  geom_polygon(data = map_data ("state"), 
               aes(x=long, y = lat,group=group),
               fill=NA,color="black",lwd = 0.7,inherit.aes = F) +
  ggtitle("Smooth coefficients of interaction") + 
  xlab("Longitude") + ylab("Latitude")
pl
```

```{r,warning=FALSE}
vis.gam(tensor_mod2, view = c("y", "x"), 
        plot.type = "persp", se = 2)
# Rotate the same plot
vis.gam(tensor_mod2, view = c("y", "x"),
        plot.type = "persp", se = 2, theta = 135)
# Make plot with 10% extrapolation
vis.gam(tensor_mod2, view = c("y", "x"),
        plot.type = "contour", too.far = 0.25)
points(dat1)

visreg(tensor_mod2)
```

# Prediction

```{r,results='hide',message=FALSE,warning=FALSE}
x_grid <- seq(-118,-104, by = 0.01)
y_grid <- seq(36,43, by = 0.01)
grid <- expand.grid(x_grid,y_grid)
grid <- data.frame(x=grid$Var2, y=grid$Var1)
preds <- predict(mod2d,newdata=grid)
preds
df <- cbind(grid,"log(Sales)" =as.data.frame(preds))
ggplot(as.data.frame(df), aes(y,x, col=preds)) +
    geom_point(alpha=0.5) +
    scale_color_gradient(low="red", high="yellow")  +
    coord_cartesian(xlim=c(-115.5, -108), ylim = c(37, 42))+
    geom_polygon( data=map_data("county"), aes(x=long, y=lat, group=group),
                  color="black", fill="lightblue", alpha=0.1 ) +
    guides(color = guide_legend(title = "log(Sales)"))
```


